### ISSUE TITLE
建议移除autofac的依赖

### ISSUE THREAD

**Issue by x-light-ai** [holdengong/EasyOffice#1]
既然使用了ServiceCollection，完全可以使用自带的，或者是再抽象一层；或者是再加一个工程，给使用autofac的作为扩展

**Comment by holdengong** [comment]
> 既然使用了ServiceCollection，完全可以使用自带的，或者是再抽象一层；或者是再加一个工程，给使用autofac的作为扩展

好的，谢谢反馈，近日内处理

**Comment by abin30** [comment]
只是测试项目里用了，不影响正式使用吧。

**Comment by holdengong** [comment]
已经移除了autofac的依赖，需要用autofac的自己populate到容器就可以了
