### ISSUE TITLE
在linux上无法运行。

### ISSUE THREAD

**Issue by whevether** [holdengong/EasyOffice#15]
在windows上可以正确到处excel,但是在编译部署到linux上就无法导出了。打印出来。_excelExportService.ExportAsync 在这步就报错了.  环境是  .net core 2.2+centos 7.6;

**Comment by holdengong** [comment]
不会吧 我这边项目都是linux啊

**Comment by whevether** [comment]
你也是centos 吗? 我开始一位是编译后的问题。可是我在mac 上编译以及在windows上编译都可以正常导出excel,就是在linux上无法导出。直接报错了

**Comment by whevether** [comment]
不好意思。我看了报错日志。是我自己搞错了。  我存放文件的路径我是大些的。后面我输出路径的时候把文件名小写了。 所以报错了 ，麻烦关闭这个issues
