### ISSUE TITLE
DTO中如果有嵌套类如何解析？

### ISSUE THREAD

**Issue by jerryjlchen** [holdengong/EasyOffice#20]
你好，
我创建了一个Computer类，在Computer类中有一个List属性的Memory类，然后在Memory类下面又有一个List属性的Manufacture类。我创建了一个Word模板，怎样依次遍历各List属性Memory中的项？以及它的子项Manufacture中的项？
非常感谢！

**Comment by holdengong** [comment]
你好，处理不了定制化的需求，需要自己处理数据
