### ISSUE TITLE
一个Word模板同时有占位符和表格数据应该怎么处理

### ISSUE THREAD

**Issue by murongqingsi** [holdengong/EasyOffice#4]
需要调用两次方法来实现嘛？

**Comment by holdengong** [comment]
模板里面可以有表格，表格里面可以有占位符，仔细看下单元测试的例子哦

**Comment by lc1055** [comment]
![Snipaste_2019-09-03_17-40-01](https://user-images.githubusercontent.com/11838290/64162456-e9c2e100-ce71-11e9-817a-0cb8711eb4dd.png)

我觉的提问者应该是上图中的意思（图中命名是随意写的），单元测试里好像没有这种使用场景：在同一个表格表单中，上部分是固定的，下部分是一个列表。

我也遇到了这种需求。
