### ISSUE TITLE
FastConvert 转换错误

### ISSUE THREAD

**Issue by x-light-ai** [holdengong/EasyOffice#5]
这个方法
public static IEnumerable<T> FastConvert<T>(this IEnumerable<ExcelDataRow> rows)
当传入的rows是不同数据时，转换出来的数据变成了一样。比如传入3条不一样的数据，转换出来的list，里面的T数据都是一样的。
断点跟踪的时候可以确定rows不一样的数据

**Comment by x-light-ai** [comment]
![image](https://user-images.githubusercontent.com/17698581/58297251-a33cff80-7e09-11e9-9a71-7353551c8c7b.png)

**Comment by x-light-ai** [comment]
![image](https://user-images.githubusercontent.com/17698581/58297313-e303e700-7e09-11e9-8330-1a9a1b97e02f.png)

**Comment by holdengong** [comment]
能否把你的模板类定义和excel发一下呢，我看你第一个截图ColName和PropertyName都是一样的，你是不是Excel中有同名的列啊

**Comment by x-light-ai** [comment]
没有同名，是不同的行，你可以看截图是0,1，2取值的。模板怎么发你呢

**Comment by holdengong** [comment]
> 没有同名，是不同的行，你可以看截图是0,1，2取值的。模板怎么发你呢

qq373317270

**Comment by holdengong** [comment]
已解决
