### ISSUE TITLE
行数读取错误，导致row为null错误

### ISSUE THREAD

**Issue by x-light-ai** [holdengong/EasyOffice#6]
![image](https://user-images.githubusercontent.com/17698581/58297421-42fa8d80-7e0a-11e9-8e8c-fc1352569081.png)

如图，excel带格式，读出的行数是非实际填写的数据。（实际填写2行+1行表头，但实际读取出是4行）
![image](https://user-images.githubusercontent.com/17698581/58297609-e2b81b80-7e0a-11e9-8e89-60619d5fd086.png)

public static ExcelDataRow Convert<TTemplate>(IRow row, ExcelHeaderRow headerRow)
此方法没有判断row可能为null的情况，然后就异常了

**Comment by holdengong** [comment]
未重现，已做容错处理
